version: '2.0'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./monitoring-configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - "GF_INSTALL_PLUGINS =grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - "./monitoring-configs/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "./monitoring-configs/provisioning:/etc/grafana/provisioning:ro"

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - "MSSQL_SA_PASSWORD=yourStrong(!)Password"
    ports:
      - "1433:1433"