scrape_configs:
  - job_name: podcastapi
    metrics_path: /metrics
    honor_labels: true
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    scrape_interval: 10s
    static_configs:
      - targets:
          - "host.docker.internal:5000"
          - "localhost:9090"