on:
  workflow_call:
    inputs:
      csproj:
        required: true
        type: string

jobs:
  build-mobile:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET 6
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
          .\dotnet-install.ps1 -Channel 6.0.3xx -Quality daily -InstallDir .

      - name: Install MAUI workload
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest https://raw.githubusercontent.com/dotnet/maui/main/NuGet.config -OutFile maui-main-NuGet.config
          & .\dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/main.json --configfile maui-main-NuGet.config

      - name: Build MAUI Mobile app
        shell: pwsh
        run: |
          & .\dotnet build ${{inputs.csproj}} -bl:mobile.binlog

      - name: Archive build log
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: '*.binlog'
